### PR TITLE
Implented original training_wizard changes on current branch

### PR DESCRIPTION
**Pull request by shterybai**

### CODE REVIEW

**Review by AlexanderZender — COMMENTED** [review]
code looks good, after testing it. I will merge it

**Comment by AlexanderZender** [comment]
The code is technically correct, but it does nothing,
The combobox selection has no impact and you do not use the query to pull the dataset types from the ontology. They are just hard coded.

**Comment by AlexanderZender** [comment]
@bican-guel @Antarctris 
Take a look, code was tested in docker
changes in the design and functionality of the upload dataset section.
please wipe databases, see wiki

**Comment by bican-guel** [comment]
**controller           | ERROR:grpclib.server:Application error
controller           | Traceback (most recent call last):
controller           |   File "/usr/local/lib/python3.9/site-packages/grpclib/server.py", line 445, in request_handler
controller           |     await method_func(stream)
controller           |   File "/app/Controller_bgrpc.py", line 647, in __rpc_create_new_user
controller           |     response = await self.create_new_user(request)
controller           |   File "/app/Controller.py", line 51, in create_new_user
controller           |     response = self._controllerManager.CreateNewUser(create_new_user_request)
controller           |   File "/app/managers/ControllerManager.py", line 47, in CreateNewUser
controller           |     dataset = CsvManager.ReadDefaultDatasetAsBytes()
controller           |   File "/app/managers/CsvManager.py", line 119, in ReadDefaultDatasetAsBytes
controller           |     file = open(os.path.join( os.path.dirname( __file__ ), "../config/defaults/titanic_train.csv"))
controller           | FileNotFoundError: [Errno 2] No such file or directory: '/app/managers/../config/defaults/titanic_train.csv'
controller           | ERROR:grpclib.server:Application error
controller           | Traceback (most recent call last):
controller           |   File "/usr/local/lib/python3.9/site-packages/grpclib/server.py", line 445, in request_handler
controller           |     await method_func(stream)
controller           |   File "/app/Controller_bgrpc.py", line 647, in __rpc_create_new_user
controller           |     response = await self.create_new_user(request)
controller           |   File "/app/Controller.py", line 51, in create_new_user
controller           |     response = self._controllerManager.CreateNewUser(create_new_user_request)
controller           |   File "/app/managers/ControllerManager.py", line 47, in CreateNewUser
controller           |     dataset = CsvManager.ReadDefaultDatasetAsBytes()
controller           |   File "/app/managers/CsvManager.py", line 119, in ReadDefaultDatasetAsBytes
controller           |     file = open(os.path.join( os.path.dirname( __file__ ), "../config/defaults/titanic_train.csv"))
controller           | FileNotFoundError: [Errno 2] No such file or directory: '/app/managers/../config/defaults/titanic_train.csv'
metaautoml_blazorboilerplate_1 exited with code 1**


This is the error i get when running it.
I removed all volumes and containers regarding mongodb according to the description in the wiki.

The **metaautoml_blazorboilerplate_1 exited with code 1** error is from the main branch the already known error which we currently need to fix.
The missing of the **titanic_train.csv** file is new.

@AlexanderZender @Antarctris , are these problems something specific to me personally or is this also a problem you two or maybe just @Antarctris also face?

**Comment by AlexanderZender** [comment]
@bican-guel are you using docker desktop to manage your docker?
And build the images with the docker compose command (without make)

I discovered with another student that without docker desktop, it does not build them identically to me.

**Comment by bican-guel** [comment]
> oh wait, i think i see the error It cant find the titanic file

Yes thats the second error i was referring to.

I will try to use docker desktop (on linux), else i will rebuild the whole project by deleting all docker files.


The blazor error is still the error we have in the Main Branch right? (Or am i miss informed?)
Because the whole Frontend-UI is not accessible because of this error (for me at least).

**Comment by AlexanderZender** [comment]
Added missing file @bican-guel 
try again pls

**Comment by bican-guel** [comment]
I have deleted the mongo database files again and tried it again. It did not work as expected.
Both previous errors are gone but now the complete page on 172.19.0.3 is not reachable. (Or which ip adress do you use?)
No error messages or any response from the terminal after the initial startup and its initial messages.

I checked the blazor docker container and it does not have any ip adress as far as i can see, is this intended?

**"Networks": {
                "metaautoml_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "blazorboilerplate",
                        "d4bdf01642ef"
                    ],
                    "NetworkID": "e6f730de9017d5f507941b70cbb2ab3213e8587794fb373b7782afe5eed0580d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }**

**Comment by bican-guel** [comment]
I also get this kind of message once in a while:

2022-06-29 19:43:54.79 spid10s     Recovery is complete. This is an informational message only. No user action is required.
2022-06-29 19:43:54.80 spid19s     The default language (LCID 0) has been set for engine and full-text services.
**2022-06-29 19:43:54.82 Logon       Error: 18456, Severity: 14, State: 38.**
2022-06-29 19:43:54.82 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'blazor_boilerplate'. [CLIENT: 172.19.0.3]
2022-06-29 19:43:55.00 spid51      [5]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2022-06-29 19:43:55.00 spid51      Starting up database 'blazor_boilerplate'.
2022-06-29 19:43:55.05 spid51      Parallel redo is started for database 'blazor_boilerplate' with worker pool size [8].
2022-06-29 19:43:55.07 spid51      Parallel redo is shutdown for database 'blazor_boilerplate' with worker pool size [8].
2022-06-29 19:43:55.19 spid51      Setting database option READ_COMMITTED_SNAPSHOT to ON for database 'blazor_boilerplate'.
2022-06-29 19:43:55.23 spid51      [5]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2022-06-29 19:43:55.23 spid51      Starting up database 'blazor_boilerplate'.
2022-06-29 19:43:55.27 spid51      Parallel redo is started for database 'blazor_boilerplate' with worker pool size [8].
2022-06-29 19:43:55.29 spid19s     The tempdb database has 8 data file(s).
2022-06-29 19:43:55.31 spid21s     Parallel redo is shutdown for database 'blazor_boilerplate' with worker pool size [8].

**Comment by bican-guel** [comment]
Deleted all docker containers and volumes and rebuild the whole project.
Now i only get the previous error from main like it used to be:

**metaautoml_blazorboilerplate_1 exited with code 1**

Again the frontend is not accessible with this error, so no testing is possible.

We should clear this up tomorrow.

**Comment by AlexanderZender** [comment]
Yes we need to see what the issue is, but I start to believe it is linux maybe

Do you have a windows machine to build it potentially?

**Comment by AlexanderZender** [comment]
I can not pin point anything that produce the behavior you are encountering, I even downloaded the current branch as zip and build from their.

I did discover an folder error within the adapter, but that does not lead to your frontend issue.

**Pull request merged**
