### PR TITLE
The layout of the page does not fit at all. This confuses the user

### PR DESCRIPTION
**Pull request by Anne19marie**
### **Issues**

1.  The layout of the page does not fit at all. This confuses the user. 

### **Solution**

- [ ] The input fields should be clearly separated from the table. It is best to place them in a separate tile. There should then be sufficient white space between this tile and the table below.

### CODE REVIEW

**Comment by AlexanderZender** [comment]
The UX is not estetic:
A: why are the names disproportial compared to the rest?
B: Why not use the card headers ? It looks squeezed together without it
C: Why is there no space at the bottom of the card?

image

**Comment by Anne19marie** [comment]
thank you, I've already corrected these little errors

**Comment by AlexanderZender** [comment]
Is this PR ready for evaluation?

**Comment by Anne19marie** [comment]
Yes it  is ready for evaluation please.

**Pull request merged**
