### PR TITLE
256 multi fidelity optimization

### PR DESCRIPTION
**Pull request by eliahvo**
Strategy "Top 3 Models"

### CODE REVIEW

**Review by AlexanderZender — DISMISSED** [review]

**Comment by AlexanderZender** [comment]
Is it intended that there is no reduction of AutoML adapter in the final training?
in the sub and main training all adapters run

**Comment by eliahvo** [comment]
Yes all adapters should run, but the sub training results should cancel most trainings in the main training.

**Comment by AlexanderZender** [comment]
Sub training:
image

Main training:
image

No reduction

**Comment by AlexanderZender** [comment]
I will investigate this later today, but can you tell me where the decision is made to abort other automl adapters in the main training?

**Comment by eliahvo** [comment]
Oh okay that is bad. In the file DataPreperationStrategy.py, there is a new function called multi_fidelity_callback(), in where we adjust in the configuration value of selected_auto_ml_solutions and selected_ml_libraries. Is there another value to be set?

**Comment by AlexanderZender** [comment]
sub training:
image

main training:
image

seem to be working, a bit weird because of how the score in the sub training is equal with 3 solutions. why did it select MLJAR but not autgluon instead ?
(I checked in the mongo DB autogluon, autosklearn and MLJAR have all 0.625 Test score.
It all works, I just wondered how it decided which one to select

**Comment by ricardone** [comment]
> sub training: image
> 
> main training: image
> 
> seem to be working, a bit weird because of how the score in the sub training is equal with 3 solutions. why did it select MLJAR but not autgluon instead ? (I checked in the mongo DB autogluon, autosklearn and MLJAR have all 0.625 Test score. It all works, I just wondered how it decided which one to select

Looks like it will just keep the order of the list if it´s the same value. Then it will pick the last 3 items of the List (small to big)

**Comment by BernhardHumm** [comment]
Why are the unselected AutoML solutions listed in the main training?

**Review by AlexanderZender — APPROVED** [review]

**Comment by AlexanderZender** [comment]
I added a new status "aborted" for training sessions in which the "loser" adapters will be canceled and not be still on standby.

@BernhardHumm Because the model entries are created the moment we start the training, we could drop the model entries of aborted models perhaps?

**Comment by BernhardHumm** [comment]
Yes, we should drop the model entries of aborted models

**Pull request merged**
