### PR TITLE
Remove AutoMLManager Inheritance and use Functional Approach

### PR DESCRIPTION
**Pull request by jnnks**
Each AutoML has a separate AutoMLManager subclass which only sets the host and port name and then calls the superclass constructor.
This PR removes the inheritance and uses a map with host and port names for each AutoML instead.

@AlexanderZender FYI

### CODE REVIEW

**Comment by AlexanderZender** [comment]
You are correct, currently they only set the appropriate HOST and PORT.
I would need to think about it and talk to Prof. Humm, if we do not have future logic that would make sense in those classes.
If none I will approve of the merge

**Comment by jnnks** [comment]
Surely we can find a solution that tackles the necessary distinction between the AutoMLs directly.
Until then we should keep the code as simple as possible.

**Review by bican-guel — APPROVED** [review]

**Comment by AlexanderZender** [comment]
As I said I will discuss it with Prof. Humm first, I don´t see why this merge couldn´t have waited until then.

**Comment by bican-guel** [comment]
Sorry my fault for the merge, i mixed up the conversations from two different PR's.
I will revert the merge and we will have the code base befor the merge.

**Comment by bican-guel** [comment]
Ok you already reverted this @AlexanderZender , sorry for the additional work. Next time i will look twice before merging a branch.

**Comment by AlexanderZender** [comment]
It is okay don't worry, when we made up a decision I will just re-merge the code.

**Comment by AlexanderZender** [comment]
After consulting with Prof. Humm. We agreed this is a good idea.
Merged.

**Pull request merged**
