### PR TITLE
Basic analysis

### PR DESCRIPTION
**Pull request by rnbndr**
Final status of the dataset_analysis team

- Added all of the discussed functionality to the analysis result file.
New: documentation of duplicate rows and columns in the analysis file.
- Refactored the code according to the changes from the persistence team 
(compare pull request: "added dataset analysis to database": https://github.com/hochschule-darmstadt/MetaAutoML/pull/114)

### CODE REVIEW

**Comment by jnnks** [comment]
Could you resolve the merge conflicts?  I don't understand some of these changes, so I am not sure what the intended behaviour is.
You probably want to use a GUI tool to merge `main` into your branch. In VSCode you can also use the commandline to trigger the merge with `git checkout  basic_analysis` and `git merge main`.

**Comment by bican-guel** [comment]
> Could you resolve the merge conflicts? I don't understand some of these changes, so I am not sure what the intended behaviour is. You probably want to use a GUI tool to merge `main` into your branch. In VSCode you can also use the commandline to trigger the merge with `git checkout basic_analysis` and `git merge main`.

I agree its best to first merge main into your branch to make sure conflicts get resolved by you (the one that knows the code best). After that a merge into main can happen easier.

**Comment by AlexanderZender** [comment]
Added a fix to the encountered crash by @bican-guel

**Comment by bican-guel** [comment]
> @bican-guel It is working afics, screenshot from mongodb compass: image

Thanks for the quick check @AlexanderZender .

I already reviewed the code so i will approve at this point.

**Review by bican-guel — APPROVED** [review]

**Pull request merged**
