### PR TITLE
Merge clean alphad3m branch into main

### PR DESCRIPTION
**Pull request by bican-guel**
Clean branch for alphad3m implementation, including all main changes.

Still encountering issues/error which is why this PR is only a draft.

### CODE REVIEW

**Comment by bican-guel** [comment]
@AlexanderZender  
As this is a draft i will mark it ready for review, to make a merge possible should you find a solution want to merge it.

**But I still encounter the above mentioned error. I am of course still working on a fix.**

**Comment by AlexanderZender** [comment]
@bican-guel Alright, thank you. I will take a look when it is ready.

**Comment by Antarctris** [comment]
The above mentioned error is the one I told about to both of you.

The problem lies by alphad3m's internal use of grpc (this is separate from our own use of grpc between the conntainers!). The grpc source contains an init function which is not simple enough to be reduced and stored away. Therefore all objects containing it can not be stored away. As far as I understand this problem is not in our source scope.

Please enlighten me If I am wrong with my findings.

**Comment by AlexanderZender** [comment]
After looking over, why are you using pickle?
We are using dill in every other component to save/load things?

**Comment by bican-guel** [comment]
> After looking over, why are you using pickle? We are using dill in every other component to save/load things?

@AlexanderZender 
I just updated the **predict.ji** file to use **dill** instead of **pickle**.

Just as a heads up, the following files still use **pickle.load()** to load stuff:
AutoCVEServer.py
AutoPytorchServer.py
AutoCVE, AutoPytorch, AutoSklearn -> predict.ji

But i am still getting the same error as mentioned above. @Antarctris I will keep on working on it this weekend and i will try to find a workaround according to the information you shared regarding the error.

**Comment by AlexanderZender** [comment]
I also added everything missing to start the process from the frontend

**Comment by bican-guel** [comment]
> @AlexanderZender Thanks for the adjustments. Now we are facing the special problems of alphad3m (loading the pipeline and problem.json properly), which we actually know how to solve.
> 
> But i need your knowledge about how and where to adjust the necessary files in the system in order to get the information i need into the **config_json** which we use in the **predict.ji** file. Can we quickly meet tomorrow before 12pm?

Nevermind i have been able to find a way to make progress. I think i can get this done by Thursday. I will try.

**Comment by bican-guel** [comment]
Code is still work in progress and throws pipeline-error at step 13. I will keep on trying later today.

**Comment by bican-guel** [comment]
@AlexanderZender 

We implemented alphad3m with tabular classification into the system, with the correct grpc-callback.
The only Error we are currently having is when we try to predict on alphad3m.

More on the Error in the alphad3m specific Issue #66

**Pull request merged**
