### PR TITLE
Evalml timeseries

### PR DESCRIPTION
**Pull request by kehuydietlatoi**
EvalML time series works in local

### CODE REVIEW

**Comment by kehuydietlatoi** [comment]
- For time series forecasting, an extra data set has to be exported, where it contains target column and a duplicate of index column, it will be more specifically in readme documented.

**Review by AlexanderZender — APPROVED** [review]

**Comment by AlexanderZender** [comment]
Was this tested? I had to make several changes to make it runable @kehuydietlatoi

**Comment by kehuydietlatoi** [comment]
@AlexanderZender with my changes i have tested it already (there is also unit test). Because of index (column is slected as index) column i have to add one extra column based on index column, but i saw that you removed it and modified the write dataset function . is it tested ?

**Comment by AlexanderZender** [comment]
@kehuydietlatoi Yes, I saw those changes and I made your code a little bit simpler. you can check it out how it is now.
I tested it, but it would be great if you build the master locally and make a test run too.

**Pull request merged**
