### PR TITLE
Remove Fixed Sizes and Add spacing.

### LINKED ISSUE #408: Small UI changes
**Reason (Why?)**
1. UI elements must be spatially separated. There must be a space between different elements.
2. Elements shall not protrude beyond their intended box. If the box is too small, the element must become smaller.
3. In a good-looking UI, all spacing must be equal. Unequal spacing leads to an unstable image.

**Solution (What?)**
1. Adding spacing to separate UI elements from each other visually.
2. Changing the fixed size of the button to a responsive size.
3. Adjust the spacing to ensure a centred font.

**Acceptance criteria**
- [x] add spacing under "Dataset Preview Configure"
image

- [x] The aim is that the button no longer overlaps on small screens.
image

- [x] left side = wrong spacing, right side = right spacing. Make spacing right.
image

### PR DESCRIPTION
**Pull request by Granoffel**
- Remove Fix Size on Trainings Button to make it responsiv. 
- Remove Fix Size on UserMenu to make the menu size expand by bigger fond. 
- Add Spacing to Save Button.

close #408

### CODE REVIEW

**Comment by AlexanderZender** [comment]
Can you merge the current Main branch first? @Granoffel

**Comment by Granoffel** [comment]
Current Main brach is merged now @AlexanderZender

**Comment by AlexanderZender** [comment]
What kind of change should i be able to observe? @Granoffel 
All the changes seem to result in the same appearance as before or is that intented?

**Comment by Granoffel** [comment]
@AlexanderZender you should be able to observe the following changes:

Befor:
image
After:
image

Befor:
image
After:
image
(The Button will still overlapp on to small screens)

Befor:
image
After:
image

**Comment by AlexanderZender** [comment]
Thank you for the clarification, something is off for me then.
I will rebuild the docker and come back

**Comment by AlexanderZender** [comment]
@Granoffel I would suggest centering the button at least:
image

**Comment by Granoffel** [comment]
@AlexanderZender good suggestion. The button is now centered at any resolution.

**Review by AlexanderZender — APPROVED** [review]

**Pull request merged**
