### PR TITLE
214 strategy ignore redundant samples

### PR DESCRIPTION
**Pull request by ricardone**
Added do_ignore_redundant_samples Strategie
Fixed do_ignore_redundant_features Strategie

### CODE REVIEW

**Comment by AlexanderZender** [comment]
The test failed, all adapters do not work. Maybe a missing import for the requirement txts?

image

**Comment by AlexanderZender** [comment]
Still will not compute models, new error @eliahvo 
image

**Comment by eliahvo** [comment]
Yes, we already fixed that error. But we noticed (as discussed earlier) that the function do never get the data "ignored_samples". But actually we are handing them over in the strategy.

**Comment by AlexanderZender** [comment]
@eliahvo I tested it with a normal dataset, everything works. Do you have a dataset to test the strategies with?

**Review by AlexanderZender — APPROVED** [review]

**Comment by eliahvo** [comment]
[train.csv](https://github.com/hochschule-darmstadt/MetaAutoML/files/10235709/train.csv)
Datenset mit doppelten Columns und Rows.

**Comment by AlexanderZender** [comment]
I believe we still have a bug here? Or is this branch ready? @eliahvo

**Comment by eliahvo** [comment]
Yes there is still a bug, but we're working on it!

**Comment by eliahvo** [comment]
@AlexanderZender Can you try it again with the new dataset called "train_original_duplicate_row.csv"? It is now working on my machine.

**Review by AlexanderZender — APPROVED** [review]

**Pull request merged**
