### PR TITLE
#474 improvement of user profile page

### PR DESCRIPTION
**Pull request by Anne19marie**
**Issue**

1.  Everything is arranged in a very confusing way. 
2.  You cannot close the profile without navigating elsewhere in the menu. 

**Tasks**
1. Everything should be placed neatly with enough distance and in different tiles. 
2. There should be an X in the top right corner or a close button to close the profile again.

### CODE REVIEW

**Comment by BernhardHumm** [comment]
Please specify all improvements of the page and discuss the specification before starting to implement

**Comment by AlexanderZender** [comment]
Why are 4 files in the root directory of the project?

**Comment by Anne19marie** [comment]
I'm sorry, I just pushed not very well , I will do it again.

**Comment by AlexanderZender** [comment]
Why did you delete the CacheManager and Launchsettings.Json.
The project can not be build without these files.

**Comment by Anne19marie** [comment]
I've already restored these files

**Comment by AlexanderZender** [comment]
A small UX issue:
image

Overlapping of field with button at least on Microsoft Edge

**Comment by Anne19marie** [comment]
Thanks, I've already solved the issue.

**Review by AlexanderZender — APPROVED** [review]

**Pull request merged**
