### PR TITLE
Eval ml implementation

### PR DESCRIPTION
**Pull request by kehuydietlatoi**
EvalML plementation.
Exported model does not work as expected in case of small data set.

### CODE REVIEW

**Comment by AlexanderZender** [comment]
Why are so many ML approaches being deleted in the Ontology?

**Comment by BernhardHumm** [comment]
Please leave deletions of entries in the ontology to Alexander Zender and 
Bernhard Humm only.

**Comment by AlexanderZender** [comment]
Can you also merge the main branch into this one first? There are some issues that are fixed in the main that prevent successful execution here.

**Comment by kehuydietlatoi** [comment]
> Can you also merge the main branch into this one first? There are some issues that are fixed in the main that prevent successful execution here.

i only changed supported by auto ml from false to true so i didn't think that it deleted some entries.. I will merge first and check why so many entries are being deleted.

**Comment by kehuydietlatoi** [comment]
@AlexanderZender  can you please review my PR, i rebased the ontology to the old version (with only one change where eval ml supported by automl ) and also fix the bug with  Woodwork input data type structure witth dev tips forwoodwork in evalml.

**Review by AlexanderZender — CHANGES_REQUESTED** [review]
Can you add comments to the test files?

**Comment by AlexanderZender** [comment]
within docker it does not work at the moment

**Comment by kehuydietlatoi** [comment]
The new tests are commited, for text task tests i encouter this bug when writing downloaded tar.gz file into disk:
image

> within docker it does not work at the moment
Maybe i see the problem , for evalml there is also extra dependencies, which must be installed (they are listed in core-requirements.txt , i added it into setupvenv already). Can  you please add the following command to dockerfile and test it (
the docker problem on my laptop is still not resolved.)
RUN pip install -r core-requirements.txt

**Review by AlexanderZender — APPROVED** [review]
working

**Pull request merged**
