### PR TITLE
added dataset analysis to database

### PR DESCRIPTION
**Pull request by AntoineMu**
Added the result of the dataset analysis to the database.
Changed datastorage function "save_dataset" to accept a dictionary as parameter instead of creating a dictionary in the function.

Created this pull request from fork because of permission errors. 
BR. Anton.

### CODE REVIEW

**Comment by jnnks** [comment]
@bican-guel I helped Anton with this PR and am happy with the changes. Do you have any input?

**Comment by bican-guel** [comment]
> @bican-guel I helped Anton with this PR and am happy with the changes. Do you have any input?

@jnnks I think the smartest way to do this would be the following:

1. First wait for the merge from MAIN into #115 (To ensure that there are no merge conflicts and everything works).
2. Then merge this branch #114 into #115 to ensure compatibility with the merge from point 1.
3. Then merge #115, which now has all working changes/commits for the dataset analysis, into the MAIN branch.

@jnnks What are your thoughts? Too much or would this be a working approach for you?

**Comment by bican-guel** [comment]
1. Has been done by @rnbndr 

I will now create a PR to merge #114  and #115 .
@rnbndr You then have to please recheck if everything works in your branch.

If @rnbndr 's response is positive we can merge #115  into MAIN.

**Comment by rnbndr** [comment]
@bican-guel To be honest I don't know how to do 2. since his code is not a branch on this project but on a cloned repository. 
Furthermore I am unable to test if it works because I can't get the project to work since a git repository has been added to the requirements.txt of the of the controller.

**Comment by bican-guel** [comment]
> @bican-guel To be honest I don't know how to do 2. since his code is not a branch on this project but on a cloned repository. Furthermore I am unable to test if it works because I can't get the project to work since a git repository has been added to the requirements.txt of the of the controller.

@rnbndr Dont worry i now merges #114 into #115 .

@rnbndr @AntoineMu Please both of you checkout branch: basic_analysis
Test if your changes work there now after the merge and report back in the #115 PR if it was successful.

**Comment by rnbndr** [comment]
grafik

I get this error when starting. This seems to originate from persistence team, maybe you know how to fix it 
@jnnks @AntoineMu  ?

**Comment by bican-guel** [comment]
> grafik
> 
> I get this error when starting. This seems to originate from persistence team, maybe you know how to fix it @jnnks @AntoineMu ?

Same for me...

**Comment by jnnks** [comment]
Oh, ok. Since when do we explicitly create users? I have never seen the function `CreateNewUser` before.

**Comment by AlexanderZender** [comment]
The error you are seeing is because:
when the frontend request a new user creation within OMA-ML an initial dataset is created for said user.
From what I see this branch changed the upload dataset logic to implement the dataset analysis, but forgot to make changes within the create user method.

@jnnks since I added it 2 weeks ago I believe.

**Comment by AlexanderZender** [comment]
I wasnt sure which of those merges is the correct one.
They seemed identical to me, I fixed your crash in the #115  one

**Pull request merged**
